package org.cso.MSBModel;


public class StructOutput {
	//Bill Printable Output Structure;
	public String     Company;
	public String     BillMonth;
	public String     BillNo;
	public String     Division;
	public String     SubDivision;
	public String     CANumber;
	public String     LegacyNumber;
	public String     MRU;
	public String     MtrMake;
	public String     Name;
	public String     Address;
	public String     PoleNo;
	public String     MtrNo;
	public String     Phase;
	public String     Category;
	public String     SanctLoad;
	public String     ConnectedLoad;
	public String     CD;
	public String     SD;
	public String     BillDays;
	public String     PreviusReading;
	public String     PrevusMtrRdgDt;
	public String     PreviusMtrReadingNote;
	public String     CurrentReading;
	public String     CurrentMtrRdgDt;
	public String     CurrentMtrReadingNote;
	public String     MF;
	public String     Consumption;
	public String     RecordedDemd;
	public String     PowerFactor;
	public String     MMCUnits;
	public String     BilledUnits;
	public String     Average;
	public String     Type;
	public String     PaymentOnAccount;
	public String     ArrearEnergyDues;
	public String     ArrearDPs;
	public String     ArrearOthers;
	public String     ArrearSubTotal_A;
	public String     CurrentEnergyCharges;
	public String     CurrentMonthDps;
	public String     FixDemdCharge;
	public String     ExcessDemdCharge;
	public String     ElectricityDuty;
	public String     MeterRent;
	public String     ShauntCapCharge;
	public String     OtherCharge;
	public String     Installment;
	public String     SubTotal_B;
	public String     InterestOnSD_C;
	public String     Incentive;
	public String     RebateOnMMC;
	public String     GrossTotal;
	public String     Rebate ;
	public String     AmtPayableUptoDt;
	public String     AmtPayableUptoAmt;
	public String     AmtPayablePYDt;
	public String     AmtPayablePYAmt;
	public String     AmtPayableAfterDt;
	public String     AmtPayableAfterAmt;
	public String     LastPaymentAmt;
	public String     LastPaidDate;
	public String     ReceiptNumber;
	public String     MESSAGE10;
	public String     MTR_READER_ID;
	public String	  PHOTO_ID;
	public String 	  Area_type;
	public String 	  MobileNo;
	public String	  REC_DATE_TIME;
	public String 	  GOVT_SUB;
	public String	  INT_DISC;
	public String 	  METER_CGST;
	public String 	  METER_SGST;
}

