package org.cso.MSBModel;

//public class StructBillInfo {
//
//	String DIV ;
//	String SUB_DIV ;
//	String SECTION ;
//	String BILL_ACC_NO  ;
//	String PRE_ACC_NO ;
//	String OLD_ACC_NO ;
//	String POLL_NO ;
//	String BILL_PERIOD;
//	double NO_OF_MONTHS ;
//	String BILLDATE  ;
//	String NAME ;
//	String ADDR1 ;
//	String ADDR2 ;
//	String ADDR3 ;
//	double SEC_DEPOSIT ;
//	String CONS_STATUS ;
//	String CATEGORY;
//	double MF  ;
//	double LOAD  ;
//	double PHASE ;
//	double PREVIOUS_READING ;
//	double PREVIOUS_MONTH ;
//	String PREVIOUS_STATUS ;
//	double OLD_MTR_FLRDG  ;
//	double NEW_MTR_ILRDG ;
//	double CURRRDG  ;
//	double CURMTH ;
//	String CUR_MTR_STATUS; 
//	String METER_NO ;
//	String MTR_OWNER ;
//	String BILLBASIS ;
//	double BILL_UNITS ;
//	String SLAB1 ;
//	String SLAB2 ;
//	String SLAB3;
//	String  SLAB4 ;
//	double EC ;
//	double FIXCHG  ;
//	double METERRENT ;
//	double ED  ;
//	double DPS ;
//	double PRE_BILL_AMT ;
//	double ARREAR_AMT ;
//	double ADJ_AMT  ;
//	double SUNDRY_AMT  ;
//	String SUNDRY_AMT_FLAG ;
//	double NET_AFT_DUEDT  ;
//	double REBOFF  ;
//	double NET_BEF_DUEDT ;
//	String REB_DT   ;
//	String DUE_DT  ;
//	String BOOKNO1  ;
//	String RECEPT_NO1 ;
//	String PMT_DT1 ;
//	double PMT_AMT1 ;
//	String BOOKNO2   ;
//	String RECEPT_NO2 ;
//	String PMT_DT2 ;
//	double PMT_AMT2 ;
//	String BOOKNO3   ;
//	String RECEPT_NO3 ;
//	String PMT_DT3 ;
//	double PMT_AMT3 ;
//	String SUND_CODE   ;
//	double ARR_SUND_AMT ;
//	double DEFERRED_AMT ;
//	double ARR_EC   ;
//	double ARR_ED    ;
//	double ARR_DPS   ;
//	}
public class StructBillInfo {

	public String DIV ;
	public String SUB_DIV ;
	public String SECTION ;
	public String BILL_ACC_NO  ;
	public String PRE_ACC_NO ;
	public String OLD_ACC_NO ;
	public String POLL_NO ;
	public String BILL_PERIOD;
	public String NO_OF_MONTHS ;
	public String BILLDATE  ;
	public String NAME ;
	public String ADDR1 ;
	public String ADDR2 ;
	public String ADDR3 ;
	public String SEC_DEPOSIT ;
	public String CONS_STATUS ;
	public String CATEGORY;
	public String MF  ;
	public String LOAD  ;
	public String PHASE ;
	public String PREVIOUS_READING ;
	public String PREVIOUS_MONTH ;
	public String PREVIOUS_STATUS ;
	public String OLD_MTR_FLRDG  ;
	public String NEW_MTR_ILRDG ;
	public String CURRRDG  ;
	public String CURMTH ;
	public String CUR_MTR_STATUS; 
	public String METER_NO ;
	public String MTR_OWNER ;
	public String BILLBASIS ;
	public String BILL_UNITS ;
	public String SLAB1 ;
	public String SLAB2 ;
	public String SLAB3;
	public String  SLAB4 ;
	public String EC ;
	public String FIXCHG  ;
	public String METERRENT ;
	public String ED  ;
	public String DPS ;
	public String PRE_BILL_AMT ;
	public String ARREAR_AMT ;
	public String ADJ_AMT  ;
	public String SUNDRY_AMT  ;
	public String SUNDRY_AMT_FLAG ;
	public String NET_AFT_DUEDT  ;
	public String REBOFF  ;
	public String NET_BEF_DUEDT ;
	public String REB_DT   ;
	public String DUE_DT  ;
	public String BOOKNO1  ;
	public String RECEPT_NO1 ;
	public String PMT_DT1 ;
	public String PMT_AMT1 ;
	public String BOOKNO2   ;
	public String RECEPT_NO2 ;
	public String PMT_DT2 ;
	public String PMT_AMT2 ;
	public String BOOKNO3   ;
	public String RECEPT_NO3 ;
	public String PMT_DT3 ;
	public String PMT_AMT3 ;
	public String SUND_CODE   ;
	public String ARR_SUND_AMT ;
	public String DEFERRED_AMT ;
	public String ARR_EC   ;
	public String ARR_ED    ;
	public String ARR_DPS   ;
	public String CONS_REF;
	public String ASD ;
	public String ASD_DUE_DT;
	}